### ISSUE TITLE
Wiki pages not available

### ISSUE THREAD

**Issue by Hau-Hau** [Brick-Abode/pldotnet#3]
Hi!

Just wanted to point an problem with wiki pages. Readme file stands that more information about configuration can be find in wikipages, however _https://github.com/Brick-Abode/pldotnet/wiki_ redirects back to _https://github.com/Brick-Abode/pldotnet_.

**Comment by rosicley** [comment]
Hi @Hau-Hau! Thank you for your feedback. Glad to let you know that we have fixed the wiki pages.
